function  out=brushpanel(STR,fighandle)
g.fh = figure('units','pixels',...
    'position',[1169 324 380 100],...
    'menubar','none',...
    'Color','w',...
    'name','Select plot regions',...
    'numbertitle','off',...
    'resize','off');
g.sub=annotation('textbox',...
    'units','pixels',...
    'position',[0 0 380 100],...
    'Tag','box',...
    'Color',[58 51 153]/255,...
    'BackgroundColor','none',...
    'String',STR,...
    'Fontsize',14,...
    'FaceAlpha',0,...
    'EdgeColor', [112 112 112]/255);
g.bg = uibuttongroup('units','pix',...
    'pos',[0 0 380 50],...
    'BorderType','line',...
    'ForegroundColor','w');
g.rd = uicontrol(g.bg,...
    'style','push',...
    'unit','pix',...
    'position',[260 15 70 22],...
    'Fontsize',8,...
    'string','Close');
g.bO = brush(fighandle);
g.axhandle=get(fighandle,'CurrentAxes');
set(g.bO,'enable','on');
set(g.rd(:),'callback',{@select,g});
uiwait(g.fh)
hBrushLine = findall(g.axhandle,'tag','Brushing');
brushedData = get(hBrushLine, {'Xdata','Ydata'});
brushedIdx = ~isnan(brushedData{1});
brushedXData = brushedData{1}(brushedIdx);
brushedYData = brushedData{2}(brushedIdx);
out=[brushedXData' brushedYData'];
close(g.fh)
function select(varargin)
g = varargin{3};
str=get(g.rd(1),'val');
if str(1)==1    
    g.st=true;
    set(g.bO,'enable','off');
end
guidata(g.fh,g.bO);
uiresume