function  buttonFig = cv_buttonpanel(fighandle,STR)

if ~exist('STR','var')
    STR = fighandle.Name;
end

if regexp(fighandle.Name,'CenterlinesPlot')
    buttonFig = figure('units','pixels',...
    'position',[1169 324 200 200],...
    'menubar','none',...
    'Color','w',...
    'name',STR,...
    'numbertitle','off',...
    'resize','off');

    polybutton(buttonFig,fighandle,2);
    datatipbutton(buttonFig,fighandle,2);
    
elseif regexp(fighandle.Name,'SelectedPoints')
    buttonFig = figure('units','pixels',...
    'position',[1169 324 200 100],...
    'menubar','none',...
    'Color','w',...
    'name',STR,...
    'numbertitle','off',...
    'resize','off');

    datatipbutton(buttonFig,fighandle,1);
    
end

function buttonHandle = polybutton(buttonFig,fighandle,nbuttons)

if nbuttons==1
    p = [0 0 1 1];
elseif nbuttons==2
    p = [0 0.5 1 0.5];
end

buttonHandle = uicontrol('Parent',buttonFig,...
    'Style','pushbutton',...
    'String','Select Data with Polygon Tool',...
    'Units','normalized',...
    'Position',p,...
    'Visible','on',...
    'Callback',{@cv_polyselect,fighandle});

function buttonHandle = datatipbutton(buttonFig,fighandle,nbuttons)

if nbuttons==1
    p = [0 0 1 1];
elseif nbuttons==2
    p = [0 0 1 0.5];
end

buttonHandle = uicontrol('Parent',buttonFig,...
    'Style','pushbutton',...
    'String','Select Data Points',...
    'Units','normalized',...
    'Position',p,...
    'Visible','on',...
    'Callback',{@cv_datatip,fighandle});

