function figH = cv_popoutwin(name)

if ~exist('name','var')
    name = 'Figure';
end

switch name
    case 'Clean Area'
    figH = figure('Visible','on', ...
        'Name', name ,...
        'NumberTitle',   'off', ...
        'IntegerHandle', 'off', ...
        'MenuBar',       'none', ...
        'Toolbar',       'none', ...
        'DockControls',  'on', ...
        'Units',         'pixels', ...
        'Color',         [1 1 1], ...
        'Tag',           'cleanareaplot',...
        'Position', [76   644   396   287]);
    
    case 'Selected Segment'
        figH = figure('Visible','on', ...
            'Name', name ,...
            'NumberTitle',   'off', ...
            'IntegerHandle', 'off', ...
            'MenuBar',       'none', ...
            'Toolbar',       'Figure', ...
            'DockControls',  'on', ...
            'Units',         'pixels', ...
            'Color',         [1 1 1], ...
            'Tag',           'cleanareaplot',...
            'Position', [1123   656   396  287]);
        cameratoolbar('Show')
        
    case 'Figure'
        figH = figure('Visible','on', ...
            'Name', name ,...
            'NumberTitle',   'off', ...
            'IntegerHandle', 'off', ...
            'MenuBar',       'none', ...
            'Toolbar',       'Figure', ...
            'DockControls',  'on', ...
            'Units',         'pixels', ...
            'Color',         [1 1 1], ...
            'Tag',           'cleanareaplot',...
            'Position', [76   644   396   287]);
        
end